# Generated by Django 3.2.7 on 2021-10-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baseline_assessment", "0002_auto_20210930_1150"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baselineassessment",
            options={"ordering": ["-created_at"]},
        ),
    ]
