# Generated by Django 3.2.7 on 2021-10-21 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("body_part", "0002_alter_bodypart_name"),
        ("session", "0002_remove_session_length"),
        ("variance", "0001_initial"),
        ("goal", "0004_goal_required"),
        ("equipment", "0006_equipmentoption"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionLength",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_session_length", models.DecimalField(decimal_places=2, max_digits=5)),
                ("total_sets", models.IntegerField()),
                ("workout_time", models.DecimalField(decimal_places=2, max_digits=5)),
                ("rest_time", models.DecimalField(decimal_places=2, max_digits=5)),
                ("warm_up_time", models.DecimalField(decimal_places=2, max_digits=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "equipment_option",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="equipment.equipmentoption"),
                ),
                ("goal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="goal.goal")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutFlow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250)),
                ("value", models.CharField(max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_length",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_flows",
                        to="controlled.sessionlength",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
