# Generated by Django 3.2.7 on 2021-10-22 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controlled", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionlength",
            name="rest_time",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="sessionlength",
            name="total_session_length",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="sessionlength",
            name="total_sets",
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name="sessionlength",
            name="warm_up_time",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="sessionlength",
            name="workout_time",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="workoutflow",
            name="value",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
