# Generated by Django 3.2.7 on 2021-10-22 15:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0002_remove_session_length"),
        ("body_part", "0002_alter_bodypart_name"),
        ("variance", "0001_initial"),
        ("controlled", "0002_auto_20211022_1056"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramDesign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                    ),
                ),
                (
                    "body_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="body_parts", to="body_part.bodypart"
                    ),
                ),
                (
                    "body_part_classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="body_part_classifications",
                        to="body_part.bodypart",
                    ),
                ),
                (
                    "sequence_flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sequences_flow",
                        to="controlled.workoutflow",
                    ),
                ),
                (
                    "session_per_week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sessions", to="session.session"
                    ),
                ),
                (
                    "variance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="variances", to="variance.variance"
                    ),
                ),
            ],
        ),
    ]
