# Generated by Django 3.2.7 on 2021-10-28 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("body_part", "0002_alter_bodypart_name"),
        ("variance", "0001_initial"),
        ("injury", "0005_alter_injury_name"),
        ("equipment", "0006_equipmentoption"),
        ("controlled", "0003_programdesign"),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlProgram",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250)),
                ("is_two_sided", models.BooleanField(default=False)),
                ("reps", models.IntegerField()),
                ("weight", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "body_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cp_body_parts",
                        to="body_part.bodypart",
                    ),
                ),
                (
                    "body_part_classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cp_body_part_classifications",
                        to="body_part.bodypart",
                    ),
                ),
                (
                    "equipment_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cp_equipment_options",
                        to="equipment.equipmentoption",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentCombination",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FirstEverCalc",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("weight_formula", models.CharField(max_length=100)),
                ("reps_formula", models.CharField(max_length=100)),
                ("type", models.CharField(choices=[("Baseline", "Baseline"), ("FSC", "FSC")], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.CharField(max_length=250)),
                (
                    "control_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cp_videos",
                        to="controlled.controlprogram",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExerciseRelationship",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("multi_weight", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "control_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="control_programs",
                        to="controlled.controlprogram",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="exercises", to="controlled.exercise"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentRelation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "equipment_combination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_combinations",
                        to="controlled.equipmentcombination",
                    ),
                ),
                (
                    "exercise_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_relations",
                        to="controlled.controlprogram",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EquipmentGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_groups",
                        to="equipment.equipment",
                    ),
                ),
                (
                    "equipment_combination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_combination_groups",
                        to="controlled.equipmentcombination",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="controlprogram",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="cp_exercises", to="controlled.exercise"
            ),
        ),
        migrations.AddField(
            model_name="controlprogram",
            name="first_set_calc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cp_first_set_calcs",
                to="controlled.firstevercalc",
            ),
        ),
        migrations.AddField(
            model_name="controlprogram",
            name="joint_injury",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="joint_injuries", to="injury.injury"
            ),
        ),
        migrations.AddField(
            model_name="controlprogram",
            name="muscle_injury",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="muscle_injuries", to="injury.injury"
            ),
        ),
        migrations.AddField(
            model_name="controlprogram",
            name="variance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="cp_variances", to="variance.variance"
            ),
        ),
    ]
