# Generated by Django 3.2.7 on 2021-10-29 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controlled", "0004_auto_20211028_1049"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="controlprogram",
            name="first_set_calc",
        ),
        migrations.RemoveField(
            model_name="controlprogram",
            name="name",
        ),
        migrations.AddField(
            model_name="controlprogram",
            name="first_set_calc_baseline",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cp_first_set_calc_baselines",
                to="controlled.firstevercalc",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="controlprogram",
            name="first_set_calc_fsc",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cp_first_sets_calc_fsc",
                to="controlled.firstevercalc",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="controlprogram",
            name="is_two_sided",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
