# Generated by Django 3.2.7 on 2021-11-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("controlled", "0005_auto_20211029_1044"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="controlprogram",
            name="first_set_calc_baseline",
        ),
        migrations.RemoveField(
            model_name="controlprogram",
            name="first_set_calc_fsc",
        ),
    ]
