# Generated by Django 3.2.7 on 2021-11-02 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controlled", "0007_alter_exerciserelationship_multi_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="firstevercalc",
            name="control_program",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fec_control_programs",
                to="controlled.controlprogram",
            ),
            preserve_default=False,
        ),
    ]
