# Generated by Django 3.2.7 on 2021-11-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controlled", "0006_auto_20211102_1324"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exerciserelationship",
            name="multi_weight",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
