# Generated by Django 3.2.7 on 2021-11-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controlled", "0007_firstevercalc_control_program"),
    ]

    operations = [
        migrations.RenameField(
            model_name="firstevercalc",
            old_name="reps_formula",
            new_name="reps_formula_string",
        ),
        migrations.RenameField(
            model_name="firstevercalc",
            old_name="weight_formula",
            new_name="weight_formula_string",
        ),
        migrations.AddField(
            model_name="firstevercalc",
            name="reps_formula_structure",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="firstevercalc",
            name="weight_formula_structure",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
