# Generated by Django 3.2.7 on 2021-11-09 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("controlled", "0008_auto_20211105_1157"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="exerciserelationship",
            unique_together={("exercise", "multi_weight")},
        ),
    ]
