# Generated by Django 3.2.7 on 2021-11-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("body_part", "0002_alter_bodypart_name"),
        ("session", "0003_auto_20211101_1039"),
        ("equipment", "0006_equipmentoption"),
        ("variance", "0001_initial"),
        ("goal", "0005_goal_gender"),
        ("controlled", "0009_alter_exerciserelationship_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="programdesign",
            unique_together={
                ("session_per_week", "sequence_flow", "day", "body_part", "body_part_classification", "variance")
            },
        ),
        migrations.AlterUniqueTogether(
            name="sessionlength",
            unique_together={
                (
                    "total_session_length",
                    "equipment_option",
                    "goal",
                    "total_sets",
                    "workout_time",
                    "rest_time",
                    "warm_up_time",
                )
            },
        ),
    ]
