# Generated by Django 3.2.7 on 2021-11-17 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variance", "0001_initial"),
        ("body_part", "0002_alter_bodypart_name"),
        ("controlled", "0011_auto_20211117_1629"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programdesign",
            name="body_part",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="body_parts",
                to="body_part.bodypart",
            ),
        ),
        migrations.AlterField(
            model_name="programdesign",
            name="body_part_classification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="body_part_classifications",
                to="body_part.bodypart",
            ),
        ),
        migrations.AlterField(
            model_name="programdesign",
            name="variance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variances",
                to="variance.variance",
            ),
        ),
    ]
