# Generated by Django 3.2.7 on 2021-11-26 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("controlled", "0011_auto_20211117_0907"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sessionlength",
            unique_together=set(),
        ),
    ]
