# Generated by Django 3.2.7 on 2021-12-22 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variance", "0001_initial"),
        ("body_part", "0002_alter_bodypart_name"),
        ("controlled", "0012_alter_sessionlength_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controlprogram",
            name="body_part_classification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cp_body_part_classifications",
                to="body_part.bodypart",
            ),
        ),
        migrations.AlterField(
            model_name="controlprogram",
            name="variance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cp_variances",
                to="variance.variance",
            ),
        ),
    ]
