# Generated by Django 3.2.7 on 2021-12-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controlled", "0014_auto_20211227_0911"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controlprogram",
            name="reps",
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name="controlprogram",
            name="weight",
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
