# Generated by Django 3.2.7 on 2021-11-18 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fitness_level", "0005_alter_fitnesslevel_fitness_number"),
        ("equipment", "0006_equipmentoption"),
        ("goal", "0005_goal_gender"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("injury", "0008_rename_status_injury_required"),
        ("standard_variable", "0004_standardvariable_data_type"),
        ("session", "0003_auto_20211101_1039"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "gym_type",
                    models.CharField(
                        blank=True,
                        choices=[("home", "home"), ("condominium", "condominium")],
                        max_length=12,
                        null=True,
                    ),
                ),
                ("longitude", models.DecimalField(blank=True, decimal_places=14, max_digits=20, null=True)),
                ("lattitude", models.DecimalField(blank=True, decimal_places=14, max_digits=20, null=True)),
                ("weights", models.JSONField(blank=True, null=True)),
                ("baseline_assessment", models.JSONField(null=True)),
                ("max_session_length", models.CharField(blank=True, max_length=3, null=True)),
                ("is_personalized", models.BooleanField(default=False)),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_equipments",
                        to="equipment.equipment",
                    ),
                ),
                (
                    "equipment_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_equipment_options",
                        to="equipment.equipmentoption",
                    ),
                ),
                (
                    "equipment_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_equipment_types",
                        to="equipment.equipment",
                    ),
                ),
                (
                    "fitness_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_fitness_levels",
                        to="fitness_level.fitnesslevel",
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_goals",
                        to="goal.goal",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_sessions",
                        to="session.session",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserStandardVariable",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=250)),
                (
                    "standard_variable_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_standard_variable",
                        to="standard_variable.standardvariable",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profiles_std_var",
                        to="v1.userprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("user_profile", "standard_variable_id")},
            },
        ),
        migrations.CreateModel(
            name="UserInjury",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "injury",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="user_injury", to="injury.injury"
                    ),
                ),
                (
                    "injury_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_injury_type",
                        to="injury.injurytype",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profile_injuries",
                        to="v1.userprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("user_profile", "injury", "injury_type")},
            },
        ),
    ]
