# Generated by Django 3.2.7 on 2021-11-23 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0007_alter_equipment_level_id"),
        ("v1", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="equipment",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="equipment_type",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="weights",
        ),
        migrations.CreateModel(
            name="UserEquipment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("weights", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_equipments",
                        to="equipment.equipment",
                    ),
                ),
                (
                    "equipment_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_equipment_types",
                        to="equipment.equipment",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profile_equipments",
                        to="v1.userprofile",
                    ),
                ),
            ],
        ),
    ]
