# Generated by Django 3.2.7 on 2021-11-29 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0004_userfeedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProgramDesign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day", models.PositiveBigIntegerField()),
                ("program_design", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("workout_date", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="user_programs", to="v1.userprofile"
                    ),
                ),
            ],
        ),
    ]
