# Generated by Django 3.2.7 on 2021-11-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0006_userequipment_weight_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprogramdesign",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprogramdesign",
            name="is_personalized",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprogramdesign",
            name="week",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
