# Generated by Django 3.2.7 on 2021-12-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0007_auto_20211130_1234"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="gym_type",
            field=models.CharField(
                blank=True,
                choices=[("home", "home"), ("condominium", "condominium"), ("commercial", "commercial")],
                max_length=12,
                null=True,
            ),
        ),
    ]
