# Generated by Django 3.2.7 on 2021-12-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0008_alter_userprofile_gym_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprogramdesign",
            name="system_rir",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
