# Generated by Django 3.2.7 on 2021-12-08 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0004_auto_20211130_0730"),
        ("v1", "0009_userprogramdesign_system_rir"),
    ]

    operations = [
        migrations.AddField(
            model_name="userfeedback",
            name="user_program_design",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_program_design",
                to="v1.userprogramdesign",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userfeedback",
            unique_together={("user_profile", "feedback", "user_program_design")},
        ),
    ]
