# Generated by Django 3.2.7 on 2021-12-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0010_auto_20211208_1313"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprogramdesign",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprogramdesign",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
