# Generated by Django 3.2.7 on 2022-01-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("v1", "0012_userstandardvariable_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_pd_exist",
            field=models.BooleanField(default=False),
        ),
    ]
