# Generated by Django 3.2.7 on 2021-10-04 14:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fitness_level", "0002_alter_fitnesslevel_options"),
        ("goal", "0002_alter_goal_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepsInReserve",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("weeks", models.CharField(max_length=250)),
                (
                    "value",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fitness_levels",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fitness_level_id",
                        to="fitness_level.fitnesslevel",
                    ),
                ),
                (
                    "goals",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="goal_id", to="goal.goal"
                    ),
                ),
            ],
        ),
    ]
