# Generated by Django 3.2.7 on 2021-10-04 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness_level", "0002_alter_fitnesslevel_options"),
        ("goal", "0002_alter_goal_options"),
        ("reps_in_reserve", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repsinreserve",
            name="fitness_levels",
        ),
        migrations.RemoveField(
            model_name="repsinreserve",
            name="goals",
        ),
        migrations.AddField(
            model_name="repsinreserve",
            name="fitness_level",
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.CASCADE, to="fitness_level.fitnesslevel"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="repsinreserve",
            name="goal",
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to="goal.goal"),
            preserve_default=False,
        ),
    ]
