# Generated by Django 3.2.7 on 2021-11-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reps_in_reserve', '0005_repsrange_repsrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repsrange',
            name='value',
            field=models.CharField(max_length=3),
        ),
    ]
