# Generated by Django 3.2.7 on 2021-12-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reps_in_reserve", "0007_alter_repsinreserve_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repsrange",
            name="value",
            field=models.PositiveIntegerField(),
        ),
    ]
