# Generated by Django 3.2.7 on 2021-10-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness_level", "0002_alter_fitnesslevel_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fitnesslevel",
            name="fitness_name",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
