# Generated by Django 3.2.7 on 2021-10-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness_level", "0003_alter_fitnesslevel_fitness_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fitnesslevel",
            name="fitness_number",
            field=models.IntegerField(unique=True),
        ),
    ]
