# Generated by Django 3.2.7 on 2021-12-30 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness_level", "0005_alter_fitnesslevel_fitness_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fitnesslevel",
            name="fitness_level",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
