# Generated by Django 3.2.7 on 2021-10-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0003_alter_equipment_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
