# Generated by Django 3.2.7 on 2021-10-12 10:35

from django.db import migrations, models

import apps.equipment.validators


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0004_alter_equipment_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=250,
                null=True,
                upload_to="media/",
                validators=[apps.equipment.validators.validate_file_size],
            ),
        ),
    ]
