# Generated by Django 3.2.7 on 2021-10-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0005_alter_equipment_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
