# Generated by Django 3.2.7 on 2021-11-22 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0006_equipmentoption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="level_id",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="equipment.equipment"
            ),
        ),
    ]
