# Generated by Django 3.2.7 on 2021-11-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0007_alter_equipment_level_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="type",
            field=models.CharField(
                choices=[("Adjustable", "Adjustable"), ("Preset 1", "Preset 1"), ("Preset 2", "Preset 2")],
                default="Preset 1",
                max_length=20,
            ),
        ),
    ]
