# Generated by Django 3.2.7 on 2021-11-29 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session", "0003_auto_20211101_1039"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="value",
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
