# Generated by Django 3.2.7 on 2021-11-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_auto_20211102_1258"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="type",
            field=models.CharField(
                choices=[("pre_session", "pre_session"), ("post_session", "post_session")],
                default="pre_session",
                max_length=20,
            ),
        ),
    ]
