# Generated by Django 3.2.7 on 2021-11-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_feedback_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="feedback",
            name="name",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name="feedback",
            unique_together={("name", "type")},
        ),
    ]
