# Generated by Django 3.2.7 on 2021-10-05 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("injury", "0002_auto_20211005_1107"),
    ]

    operations = [
        migrations.AlterField(
            model_name="injury",
            name="injury_type",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="injury.injurytype"),
            preserve_default=False,
        ),
    ]
