# Generated by Django 3.2.7 on 2021-10-08 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("injury", "0002_alter_injury_options"),
        ("injury", "0003_alter_injury_injury_type"),
    ]

    operations = []
