# Generated by Django 3.2.7 on 2021-10-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("injury", "0004_merge_20211008_0600"),
    ]

    operations = [
        migrations.AlterField(
            model_name="injury",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
