# Generated by Django 3.2.7 on 2021-10-29 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("injury", "0005_alter_injury_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="injury",
            name="injury_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="injuries_type", to="injury.injurytype"
            ),
        ),
    ]
