# Generated by Django 3.2.7 on 2021-11-08 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("injury", "0007_injury_body_part"),
    ]

    operations = [
        migrations.RenameField(
            model_name="injury",
            old_name="status",
            new_name="required",
        ),
    ]
