# Generated by Django 3.2.7 on 2021-10-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standard_variable", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standardvariable",
            name="ui_control_type",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
