# Generated by Django 3.2.7 on 2021-10-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standard_variable", "0002_alter_standardvariable_ui_control_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="standardvariable",
            name="is_personalized",
            field=models.BooleanField(default=False),
        ),
    ]
