# Generated by Django 3.2.7 on 2021-11-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard_variable', '0003_standardvariable_is_personalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardvariable',
            name='data_type',
            field=models.CharField(default='int', max_length=250),
            preserve_default=False,
        ),
    ]
