# Generated by Django 3.2.7 on 2021-10-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goal", "0003_alter_goal_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="required",
            field=models.BooleanField(default=True),
        ),
    ]
