# Generated by Django 3.2.7 on 2021-10-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goal", "0004_goal_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Both", "Both")], default="Both", max_length=20
            ),
        ),
    ]
